# Exported from Render on 2024-09-04T15:50:04Z
services:
- type: web
  name: hotel
  runtime: node
  repo: https://github.com/Rahul-2148/node_hotels
  plan: free
  envVars:
  - key: MONGODB_URL_LOCAL
    sync: false
  - key: MONGODB_URL
    sync: false
  - key: PORT
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node server.js
version: "1"
